name: deploy to zeit
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed, merged]
    branches:
      - master
jobs:   
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: amondnet/now-deployment@v1
        if: github.action == 'closed' && github.pull_request.merged == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-args: '--prod'
